/**
 * Bridge → bridge envelope forwarder.
 *
 * When an authenticated bridge sends `kind: 'outbound_envelope'` over its
 * WebSocket, the gateway must route that envelope to the recipient agent
 * (look up their tenant + dispatch as inbound). Without this, replies
 * generated by adapters that reach the bridge via the WS-only outbound
 * path are silently dropped.
 *
 * This is the same logical path POST /didcomm uses, but the recipient is
 * resolved from the envelope's `to[]` field instead of the Host header.
 */

import { agents, toTenantId, withTenant, type CloudDbClient } from '@kybernesis/arp-cloud-db';
import { eq } from 'drizzle-orm';
import { resolvePendingFromEnvelope, type PushContext } from './push.js';
import { dispatchInbound, type DispatchContext, type PeerResolver } from './dispatch.js';
import type { PostgresAudit } from './audit.js';
import type { SessionRegistry } from './sessions.js';
import type { CloudRuntimeLogger, TenantMetrics, WsClientEvent } from './types.js';
import type { Pdp } from '@kybernesis/arp-pdp';

export interface ForwardOptions {
  /** AgentID S4: push-delivery context (JWS signer + sealing key); optional. */
  push?: PushContext;
  db: CloudDbClient;
  sessions: SessionRegistry;
  pdp: Pdp;
  resolver: PeerResolver;
  logger: CloudRuntimeLogger;
  metrics: TenantMetrics;
  auditFactory: (tenantDbForAgent: ReturnType<typeof withTenant>) => PostgresAudit;
  now?: () => number;
}

/**
 * AgentID S4: deliver an already-signed envelope to a peer hosted on this
 * gateway (cloud-to-cloud). Returns the recipient-side dispatch result, or
 * null when the peer is not hosted here. Used by the WS outbound path and by
 * push-mode replies / agent-API sends.
 */
export function createForwardEnvelope(opts: ForwardOptions) {
  const now = opts.now ?? (() => Date.now());
  return async function forwardEnvelope(params: {
    peerDid: string;
    envelope: string;
  }): Promise<Awaited<ReturnType<typeof dispatchInbound>> | null> {
    const rows = await opts.db
      .select({ tenantId: agents.tenantId, did: agents.did })
      .from(agents)
      .where(eq(agents.did, params.peerDid))
      .limit(1);
    const recipient = rows[0];
    if (!recipient) {
      // AgentID S5: an external (non-hosted) caller may be waiting on this
      // reply via the A2A endpoint or the agent-API.
      if (resolvePendingFromEnvelope(params.envelope)) {
        return { ok: true, decision: 'allow', queued: false };
      }
      return null;
    }
    const recipientTenantDb = withTenant(opts.db, toTenantId(recipient.tenantId));
    const ctx: DispatchContext = {
      tenantDb: recipientTenantDb,
      tenantId: recipient.tenantId,
      agentDid: recipient.did,
      audit: opts.auditFactory(recipientTenantDb),
      pdp: opts.pdp,
      resolver: opts.resolver,
      sessions: opts.sessions,
      logger: opts.logger,
      metrics: opts.metrics,
      now,
      ...(opts.push ? { push: opts.push } : {}),
    };
    return dispatchInbound(ctx, params.envelope);
  };
}

export function createForwardOutboundEnvelope(opts: ForwardOptions) {
  const now = opts.now ?? (() => Date.now());
  return async function forwardOutbound(params: {
    tenantId: string;
    agentDid: string;
    event: Extract<WsClientEvent, { kind: 'outbound_envelope' }>;
  }): Promise<void> {
    const { event } = params;
    const log = opts.logger.child({
      senderTenantId: params.tenantId,
      senderAgentDid: params.agentDid,
      msgId: event.msgId,
    });
    if (!event.envelope || !event.peerDid) {
      log.warn({}, 'outbound_envelope_invalid');
      return;
    }
    // Look up recipient agent → recipient tenant.
    const rows = await opts.db
      .select({ tenantId: agents.tenantId, did: agents.did })
      .from(agents)
      .where(eq(agents.did, event.peerDid))
      .limit(1);
    const recipient = rows[0];
    if (!recipient) {
      log.warn({ peerDid: event.peerDid }, 'outbound_envelope_unknown_recipient');
      return;
    }
    const recipientTenantDb = withTenant(opts.db, toTenantId(recipient.tenantId));
    const ctx: DispatchContext = {
      tenantDb: recipientTenantDb,
      tenantId: recipient.tenantId,
      agentDid: recipient.did,
      audit: opts.auditFactory(recipientTenantDb),
      pdp: opts.pdp,
      resolver: opts.resolver,
      sessions: opts.sessions,
      logger: opts.logger,
      metrics: opts.metrics,
      now,
    };
    const result = await dispatchInbound(ctx, event.envelope);
    if (!result.ok) {
      log.warn({ reason: result.reason, recipient: recipient.did }, 'outbound_envelope_denied');
    }
  };
}
