import { redirect } from 'next/navigation';
import { Header } from '@/components/Header';
import { getSession } from '@/lib/session';
import { QrScanner } from './QrScanner';

export const dynamic = 'force-dynamic';

export default async function ScanPage() {
  if (!(await getSession())) redirect('/login');
  return (
    <div>
      <Header />
      <h2 className="mb-4 text-lg font-semibold">Scan invitation</h2>
      <p className="mb-4 max-w-xl text-sm text-arp-muted">
        Point your device camera at the QR code generated by your pairing
        partner. Scanning navigates straight to the consent review screen.
      </p>
      <QrScanner />
    </div>
  );
}
